language: minimal
sudo: required
services:
- docker
before_install: 
  - "docker build -t farp32/docker-react -f Dockerfile.dev ."
script: 
  - "docker run farp32/docker-react npm run test -- --coverage"
services: 
  - docker
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-693926819406"
  bucket_path: "docker-react"
  on:
    branch: master
  
sudo: required
